name: CI Pipeline
on: 
  push:
Jobs:
  build:
  runs-on: ubuntu-latest

  steps:
  - uses: actions/checkout@v3
  - uses: actions/setup-python@v4
    with:
      pyhton-version: 3.11
  - uses: iterative/setup-cml@v2

  - name: Install Dependencies
    run:
      python -m pip install --upgrade pip
      pip install -r requirements.txt
  - name: Run mainfile
    run:
      python main.py
  - name: Run Tests
    run:
      python -m unittest discover
  - name: Create CML report
    env:
      REPO_TOKEN: ${{secrets GITHUB_TOKEN}}
    run:
      echo "# First line of our report" >> report.md
      echo "## Bar Plots" >> reports.md
      echo '![](./bars.png "Bar plot")' >> report.md
      echo "## Line Plots" >> report.md
      echo '![](./lines.png "Bar plot")' >> report.md
      cml comment create report.md 